-- MySQL Script generated by MySQL Workbench
-- Wed Oct 22 21:21:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema epig_seguros
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `epig_seguros` ;

-- -----------------------------------------------------
-- Schema epig_seguros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `epig_seguros` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `epig_seguros` ;

-- -----------------------------------------------------
-- Table `epig_seguros`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `epig_seguros`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `epig_seguros`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `tipo` CHAR(1) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `idusuarios_UNIQUE` (`id_usuario` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
